---
driver_plugin: vagrant
driver_config:
  customize:
    memory: 1024

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04-nochef
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
    require_chef_omnibus: 11.6.0
    network:
      - ["private_network", {ip: "11.12.14.11"}]
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
    - recipe[nvm_test::default]
    - recipe[minitest-handler]
- name: nvm-install
  run_list:
    - recipe[nvm_test::nvm_install]
    - recipe[minitest-handler]
- name: nvm-alias-default
  run_list:
    - recipe[nvm_test::nvm_alias_default]
    - recipe[minitest-handler]
- name: nvm-install-from-source
  run_list:
    - recipe[nvm_test::nvm_install_from_source]
    - recipe[minitest-handler]