language: ruby
rvm:
#  - 1.8.7
  - 1.9.3 
script: "bundle exec rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.0.3
notifications:
  email: false
bundler_args: --without integration
